{{- if .Values.keycloak.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "apisix-poc.keycloak.fullname" . }}-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "apisix-poc.labels" . | nindent 4 }}
    app.kubernetes.io/component: keycloak
type: Opaque
data:
  admin-username: {{ .Values.keycloak.auth.adminUser | b64enc }}
  admin-password: {{ .Values.keycloak.auth.adminPassword | b64enc }}
  db-username: {{ .Values.keycloak.database.username | b64enc }}
  db-password: {{ .Values.keycloak.database.password | b64enc }}
{{- end }}
